//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTTimeRentWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPVersionManagement
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Version { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public long OperatorID { get; set; }
        public int IsNecessary { get; set; }
        public string UpdateUrl { get; set; }
        public string Notes { get; set; }
    }
}
