//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTTimeRentWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BalanceSeriel
    {
        public long Id { get; set; }
        public Nullable<long> Balances_Id { get; set; }
        public Nullable<long> Order_Id { get; set; }
        public Nullable<long> ChargeSerielId { get; set; }
        public Nullable<double> DeductFee { get; set; }
        public int Classify { get; set; }
        public string PayName { get; set; }
        public string PaymentAccount { get; set; }
        public Nullable<long> PayMethod_Id { get; set; }
        public Nullable<long> AdditionMoney_Id { get; set; }
        public System.DateTime CreatTime { get; set; }
    }
}
