//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTTimeRentWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car_Class
    {
        public long Id { get; set; }
        public string CarName { get; set; }
        public string Code { get; set; }
        public string CarBrand { get; set; }
        public string EnduranceMileage { get; set; }
        public string Type { get; set; }
        public string SeatSize { get; set; }
        public string FuelType { get; set; }
        public string Battery { get; set; }
        public string CarPic { get; set; }
        public string AT_MT { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string RatedPower { get; set; }
        public string MaximumPower { get; set; }
        public string WDH { get; set; }
        public string Wheelbase { get; set; }
        public string CurbWeight { get; set; }
        public string PeopleNum { get; set; }
        public string MaximumSpeed { get; set; }
        public string MaximumClimb { get; set; }
        public string MotorRatedSpeed { get; set; }
        public string MotorMaximumSpeed { get; set; }
        public string BodyColor { get; set; }
        public string BatteryConfig { get; set; }
        public string Motor { get; set; }
        public string ChargeMode { get; set; }
        public string ChargeForm { get; set; }
        public string ChargePower { get; set; }
        public string SwitchForm { get; set; }
        public string TransmissionForm { get; set; }
        public string Describe { get; set; }
    }
}
