//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTTimeRentWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarTBoxRelationShip
    {
        public long Id { get; set; }
        public Nullable<long> CarId { get; set; }
        public string TBoxMac { get; set; }
        public string TBoxName { get; set; }
        public string TBoxNumber { get; set; }
        public int Status { get; set; }
        public long OperatorId { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
