//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTTimeRentWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargeSeriel
    {
        public long Id { get; set; }
        public long Account_Id { get; set; }
        public Nullable<int> AccountClass { get; set; }
        public double Money { get; set; }
        public int Classify { get; set; }
        public int Type { get; set; }
        public string BuyerId { get; set; }
        public string SellerId { get; set; }
        public string OutTradeNo { get; set; }
        public int TradeStatus { get; set; }
        public string TradeNo { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
