//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTTimeRentWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public long Id { get; set; }
        public decimal CouponMoney { get; set; }
        public decimal MinMoney { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int Status { get; set; }
        public System.DateTime Starttime { get; set; }
        public System.DateTime Endtime { get; set; }
        public int OrderType { get; set; }
        public int Type { get; set; }
        public long CreateAccountID { get; set; }
        public int SType { get; set; }
        public Nullable<long> FranchiseeID { get; set; }
        public Nullable<long> ShopAdminID { get; set; }
        public Nullable<long> ShopID { get; set; }
    }
}
