//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTTimeRentWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepositRelation
    {
        public long Id { get; set; }
        public string DepositName { get; set; }
        public double DepositValue { get; set; }
        public Nullable<long> CarClassId { get; set; }
        public int Classify { get; set; }
        public int Status { get; set; }
        public Nullable<long> OperatorId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Note { get; set; }
    }
}
