//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTTimeRentWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FestivalDates
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string SolarDate { get; set; }
        public Nullable<int> TotalDays { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string LunarDate { get; set; }
        public Nullable<int> DaysOf { get; set; }
    }
}
