//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTTimeRentWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public long Id { get; set; }
        public Nullable<long> Shop_Id { get; set; }
        public long Account_Id { get; set; }
        public Nullable<long> CarClass_Id { get; set; }
        public Nullable<long> Car_Id { get; set; }
        public System.DateTime CreatTime { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public long PickupShop_Id { get; set; }
        public long ReturnShop_Id { get; set; }
        public Nullable<double> OrderDeposit { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public Nullable<int> PayStatus { get; set; }
        public Nullable<int> IsPrinted { get; set; }
        public Nullable<int> PayWay { get; set; }
        public string E_Signature { get; set; }
        public string OrderNum { get; set; }
        public Nullable<double> OrderMoney { get; set; }
        public Nullable<double> BudgetCost { get; set; }
        public Nullable<int> OrderCategory { get; set; }
        public Nullable<long> Coupon_Id { get; set; }
    }
}
