//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTTimeRentWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivilegeRelation
    {
        public long Id { get; set; }
        public long Acc_ClassifyID { get; set; }
        public long Privilege_Id { get; set; }
        public Nullable<double> Money { get; set; }
        public double Proportion { get; set; }
        public System.DateTime STime { get; set; }
        public Nullable<System.DateTime> ETime { get; set; }
        public long OperatorID { get; set; }
        public int Status { get; set; }
    }
}
