//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTTimeRentWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provinces
    {
        public long Id { get; set; }
        public string areaname { get; set; }
        public string parentno { get; set; }
        public string areacode { get; set; }
        public int arealevel { get; set; }
        public string typename { get; set; }
        public Nullable<int> status { get; set; }
    }
}
