//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTTimeRentWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialVehicleUsage
    {
        public long Id { get; set; }
        public long OrderId { get; set; }
        public Nullable<double> AmountOfMoney { get; set; }
        public long PartnerId { get; set; }
        public string ConsumptionNo { get; set; }
        public Nullable<int> PaymentMethod { get; set; }
        public int PaymentStatus { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> PaymentTime { get; set; }
    }
}
