//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTTimeRentWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class TimeRentEntities : DbContext
    {
        public TimeRentEntities()
            : base("name=TimeRentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Acc_Classify> Acc_Classify { get; set; }
        public DbSet<Acc_Fran_Bind> Acc_Fran_Bind { get; set; }
        public DbSet<Acc_Shop_Bind> Acc_Shop_Bind { get; set; }
        public DbSet<Account> Account { get; set; }
        public DbSet<AdditionDicBind> AdditionDicBind { get; set; }
        public DbSet<AdditionMoney> AdditionMoney { get; set; }
        public DbSet<AdditionMoneySeriel> AdditionMoneySeriel { get; set; }
        public DbSet<APPVersionManagement> APPVersionManagement { get; set; }
        public DbSet<AuditRecord> AuditRecord { get; set; }
        public DbSet<Balances> Balances { get; set; }
        public DbSet<BalanceSeriel> BalanceSeriel { get; set; }
        public DbSet<CancelOrder> CancelOrder { get; set; }
        public DbSet<CancelRule> CancelRule { get; set; }
        public DbSet<Car_Class> Car_Class { get; set; }
        public DbSet<CarDeposit> CarDeposit { get; set; }
        public DbSet<CarLeasePrice> CarLeasePrice { get; set; }
        public DbSet<CarLog> CarLog { get; set; }
        public DbSet<CarRentalUsersClassify> CarRentalUsersClassify { get; set; }
        public DbSet<Cars> Cars { get; set; }
        public DbSet<Cars_Reserved> Cars_Reserved { get; set; }
        public DbSet<CarTBoxRelationShip> CarTBoxRelationShip { get; set; }
        public DbSet<ChargeSeriel> ChargeSeriel { get; set; }
        public DbSet<CompanyPersonalBinding> CompanyPersonalBinding { get; set; }
        public DbSet<Coupon> Coupon { get; set; }
        public DbSet<CouponAccountBind> CouponAccountBind { get; set; }
        public DbSet<CouponDicBind> CouponDicBind { get; set; }
        public DbSet<DamageInspection> DamageInspection { get; set; }
        public DbSet<DamageInspectionRules> DamageInspectionRules { get; set; }
        public DbSet<DayPriceRule> DayPriceRule { get; set; }
        public DbSet<DepositRelation> DepositRelation { get; set; }
        public DbSet<DevicesRecord> DevicesRecord { get; set; }
        public DbSet<DicountTable> DicountTable { get; set; }
        public DbSet<Dictionary> Dictionary { get; set; }
        public DbSet<DictionaryDetail> DictionaryDetail { get; set; }
        public DbSet<DiscountPic> DiscountPic { get; set; }
        public DbSet<DoorPassword> DoorPassword { get; set; }
        public DbSet<ExtraFee> ExtraFee { get; set; }
        public DbSet<ExtraFee_Instance> ExtraFee_Instance { get; set; }
        public DbSet<FaultHandlingRecord> FaultHandlingRecord { get; set; }
        public DbSet<Feedback> Feedback { get; set; }
        public DbSet<FestivalDates> FestivalDates { get; set; }
        public DbSet<Franchisees> Franchisees { get; set; }
        public DbSet<GroupAccount> GroupAccount { get; set; }
        public DbSet<GroupBalance> GroupBalance { get; set; }
        public DbSet<GroupBalanceFlow> GroupBalanceFlow { get; set; }
        public DbSet<InsuranceSeriel> InsuranceSeriel { get; set; }
        public DbSet<Invoice> Invoice { get; set; }
        public DbSet<InvoiceTemplate> InvoiceTemplate { get; set; }
        public DbSet<Menu> Menu { get; set; }
        public DbSet<MenuRights> MenuRights { get; set; }
        public DbSet<MoneyProportion> MoneyProportion { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<OrderChange> OrderChange { get; set; }
        public DbSet<OrderMsg> OrderMsg { get; set; }
        public DbSet<Partners> Partners { get; set; }
        public DbSet<PayMethod> PayMethod { get; set; }
        public DbSet<PeccancyDeposit> PeccancyDeposit { get; set; }
        public DbSet<PeccancyInspection> PeccancyInspection { get; set; }
        public DbSet<PersonalDepositUsage> PersonalDepositUsage { get; set; }
        public DbSet<Pickup_Return> Pickup_Return { get; set; }
        public DbSet<PostageInvoiceRelationship> PostageInvoiceRelationship { get; set; }
        public DbSet<Privilege> Privilege { get; set; }
        public DbSet<PrivilegeRelation> PrivilegeRelation { get; set; }
        public DbSet<PromotionPic> PromotionPic { get; set; }
        public DbSet<Provinces> Provinces { get; set; }
        public DbSet<RechargeRecord> RechargeRecord { get; set; }
        public DbSet<RegistTextMsg> RegistTextMsg { get; set; }
        public DbSet<RentCarPackage> RentCarPackage { get; set; }
        public DbSet<RentCarShopBind> RentCarShopBind { get; set; }
        public DbSet<ReturnCar> ReturnCar { get; set; }
        public DbSet<SecurityDeposit> SecurityDeposit { get; set; }
        public DbSet<SecurityDepositSeriel> SecurityDepositSeriel { get; set; }
        public DbSet<Shop_Manage> Shop_Manage { get; set; }
        public DbSet<ShopAdmin> ShopAdmin { get; set; }
        public DbSet<ShopRentPrice> ShopRentPrice { get; set; }
        public DbSet<ShopReturnWay> ShopReturnWay { get; set; }
        public DbSet<Shops> Shops { get; set; }
        public DbSet<SMSTextMsg> SMSTextMsg { get; set; }
        public DbSet<SpecialVehicleUsage> SpecialVehicleUsage { get; set; }
        public DbSet<SystemMessage> SystemMessage { get; set; }
        public DbSet<TBoxPassword> TBoxPassword { get; set; }
        public DbSet<TextMsg> TextMsg { get; set; }
        public DbSet<TimeGradientPrice> TimeGradientPrice { get; set; }
        public DbSet<TimeOutOrder> TimeOutOrder { get; set; }
        public DbSet<UnitTimePriceRule> UnitTimePriceRule { get; set; }
        public DbSet<UsefulCarRemind> UsefulCarRemind { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<UserDeposit> UserDeposit { get; set; }
        public DbSet<UserDepositSeriels> UserDepositSeriels { get; set; }
        public DbSet<UserZMXY> UserZMXY { get; set; }
        public DbSet<VehicleFaultInfo> VehicleFaultInfo { get; set; }
        public DbSet<VehicleVerificationCode> VehicleVerificationCode { get; set; }
        public DbSet<Personal_Order> Personal_Order { get; set; }
        public DbSet<Provinces_Shops_View> Provinces_Shops_View { get; set; }
        public DbSet<Test_View> Test_View { get; set; }
    
        public virtual int GetAllCoupon(string accountID, string selectTime, string accountType, string carClassID, string money, string oType)
        {
            var accountIDParameter = accountID != null ?
                new ObjectParameter("AccountID", accountID) :
                new ObjectParameter("AccountID", typeof(string));
    
            var selectTimeParameter = selectTime != null ?
                new ObjectParameter("SelectTime", selectTime) :
                new ObjectParameter("SelectTime", typeof(string));
    
            var accountTypeParameter = accountType != null ?
                new ObjectParameter("AccountType", accountType) :
                new ObjectParameter("AccountType", typeof(string));
    
            var carClassIDParameter = carClassID != null ?
                new ObjectParameter("CarClassID", carClassID) :
                new ObjectParameter("CarClassID", typeof(string));
    
            var moneyParameter = money != null ?
                new ObjectParameter("Money", money) :
                new ObjectParameter("Money", typeof(string));
    
            var oTypeParameter = oType != null ?
                new ObjectParameter("OType", oType) :
                new ObjectParameter("OType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetAllCoupon", accountIDParameter, selectTimeParameter, accountTypeParameter, carClassIDParameter, moneyParameter, oTypeParameter);
        }
    
        public virtual int GetAllCoupon_Shop(string accountID, string selectTime, string accountType, string carClassID, string money, string oType, string shopID)
        {
            var accountIDParameter = accountID != null ?
                new ObjectParameter("AccountID", accountID) :
                new ObjectParameter("AccountID", typeof(string));
    
            var selectTimeParameter = selectTime != null ?
                new ObjectParameter("SelectTime", selectTime) :
                new ObjectParameter("SelectTime", typeof(string));
    
            var accountTypeParameter = accountType != null ?
                new ObjectParameter("AccountType", accountType) :
                new ObjectParameter("AccountType", typeof(string));
    
            var carClassIDParameter = carClassID != null ?
                new ObjectParameter("CarClassID", carClassID) :
                new ObjectParameter("CarClassID", typeof(string));
    
            var moneyParameter = money != null ?
                new ObjectParameter("Money", money) :
                new ObjectParameter("Money", typeof(string));
    
            var oTypeParameter = oType != null ?
                new ObjectParameter("OType", oType) :
                new ObjectParameter("OType", typeof(string));
    
            var shopIDParameter = shopID != null ?
                new ObjectParameter("ShopID", shopID) :
                new ObjectParameter("ShopID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetAllCoupon_Shop", accountIDParameter, selectTimeParameter, accountTypeParameter, carClassIDParameter, moneyParameter, oTypeParameter, shopIDParameter);
        }
    
        public virtual int GetAllOverCoupon(string accountID, string selectTime, string accountType)
        {
            var accountIDParameter = accountID != null ?
                new ObjectParameter("AccountID", accountID) :
                new ObjectParameter("AccountID", typeof(string));
    
            var selectTimeParameter = selectTime != null ?
                new ObjectParameter("SelectTime", selectTime) :
                new ObjectParameter("SelectTime", typeof(string));
    
            var accountTypeParameter = accountType != null ?
                new ObjectParameter("AccountType", accountType) :
                new ObjectParameter("AccountType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetAllOverCoupon", accountIDParameter, selectTimeParameter, accountTypeParameter);
        }
    
        public virtual ObjectResult<GetCarPrice_Result> GetCarPrice(Nullable<long> shopid, Nullable<long> carclassid)
        {
            var shopidParameter = shopid.HasValue ?
                new ObjectParameter("shopid", shopid) :
                new ObjectParameter("shopid", typeof(long));
    
            var carclassidParameter = carclassid.HasValue ?
                new ObjectParameter("carclassid", carclassid) :
                new ObjectParameter("carclassid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCarPrice_Result>("GetCarPrice", shopidParameter, carclassidParameter);
        }
    
        public virtual ObjectResult<OnlyGetCarPrice_Result> OnlyGetCarPrice(Nullable<long> shopid, Nullable<long> carclassid)
        {
            var shopidParameter = shopid.HasValue ?
                new ObjectParameter("shopid", shopid) :
                new ObjectParameter("shopid", typeof(long));
    
            var carclassidParameter = carclassid.HasValue ?
                new ObjectParameter("carclassid", carclassid) :
                new ObjectParameter("carclassid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OnlyGetCarPrice_Result>("OnlyGetCarPrice", shopidParameter, carclassidParameter);
        }
    }
}
