//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTTimeRentWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long Id { get; set; }
        public long Account_Id { get; set; }
        public string Tel { get; set; }
        public string Name { get; set; }
        public string Avatar { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Email { get; set; }
        public Nullable<int> Status { get; set; }
        public string ID_CardNum { get; set; }
        public string ID_CardPic { get; set; }
        public string Driver_License { get; set; }
        public string InviteCode { get; set; }
        public string ID_CardFront { get; set; }
        public Nullable<System.DateTime> Driver_LicenseDate { get; set; }
        public Nullable<int> IDPicStatus { get; set; }
        public Nullable<int> DriverPicStatus { get; set; }
        public string HandheldCreditCard { get; set; }
        public string CreditCard { get; set; }
        public Nullable<int> CreditCardStatus { get; set; }
        public string PortraitPic { get; set; }
        public Nullable<int> PortraitStatus { get; set; }
    }
}
