//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTTimeRentWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleFaultInfo
    {
        public long Id { get; set; }
        public string CarNumber { get; set; }
        public Nullable<int> Rank { get; set; }
        public string FaultName { get; set; }
        public System.DateTime Time { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public int Status { get; set; }
        public string Remark_1 { get; set; }
        public string Remark_2 { get; set; }
        public string Remark_3 { get; set; }
    }
}
